### ISSUE TITLE
Velocity range

### ISSUE THREAD

**Issue by AlexFundorin** [RobU23/ReaScripts#24] opened 2020-04-22 08:14 UTC
Can you, please, fix the velocity range slider, so that it  won't only generate min/max values for the note but also the mid values?

**Comment by RobU23** [comment] 2020-04-23 20:37
Hi Alex - It's not broken! :)  It was designed to emulate the velocity functionality of xox/303 type sequencers which only had an accent option.  It is very unlikely that I will add this functionality to the current version, but it has been requested before and will be in version 2.

Cheers
Rob

**Comment by AlexFundorin** [comment] 2020-04-24 04:14
I see. Thanks. I have a couple more questions:
Why randomiser is a default window, considering that it's "generate" button" doesn't generate anything and forces user to switch tab first?
Why DEM is always resetting the key and "octave" to с chromatic 3?
I've changed the root octave in the MIDI Editor, so it would correspond to GM, i.e., octave 4 is 3 now (name display offset in preferences). Can we make DEM to consider that window and display the octave numbers accordingly?
Is it possible to add note weight presets for the randomiser? More than 2 octaves range for randomiser?
1/32 note lengths for the sequencer?
Save default velocity range? I don't need 127, most of the time, since it's changing the main timbre drastically.
Thanks in advance.

**Comment by RobU23** [comment] 2020-04-30 12:02
Randomiser is the default tab because originally there was only a pitch randomiser (see 'MIDI Note Randomiser on the Reaper forums).

When does it reset the key and octave?  These should be preserved in a project, but not across projects.

Reaper is somewhat unique in that it allows the user to offset the midi octave.  MExM v1 does not take this into account, but MExM v2 will.  The functionality will not be added to v1.

Presets for scales, and other things have been requested many times : )  The answer is that you'll have to wait for v2.  The longer answer is that the current codebase is a mess and hard to maintain making it very difficult to add.

The plan for v2 is to 2 octaves of visible sliders (toggle between 1 or 2) so you could either have the 2nd octave randomly generated from the 1st octave (current behaviour), or explicitly input values for the 2nd octave via sliders.

The way the engine is currently, 32nd notes are a pain in the hoop. From a musical pov, I can't say I use them often, but I'll think about it for v2 (also triplets, etc).

Velocity range should be remembered in the project.  For v2, I can have a preference for that.

Also for v2; many many more scales, presets, item based settings, user options, much better GUI, and more.  Don't hold your breath, it is some way away yet... : )

**Closed as completed by RobU23** 2020-04-30 12:02 UTC
